image: "archlinux:latest"

before_script:
    - >
      pacman -Syu --needed --noconfirm
      make base-devel python python-pkgconfig
      python-pytest python-pytest-cov python-pytest-pacman
      python-sphinx python-pylint


stages:
  - lint
  - test
  - doc


lint:
  script:
    - make lint
  except:
    - schedules


test:
  script:
    - make build
    - PYTEST_OPTIONS="--junitxml=report.xml --cov-report xml" make test
  artifacts:
    when: always
    reports:
      junit: report.xml
      cobertura: coverage.xml
  except:
    - schedules

next:
  only:
    - schedules
  script:
    - pacman -Syu --needed --noconfirm meson git
    - git clone https://gitlab.archlinux.org/pacman/pacman.git
    - cd pacman && mkdir build && cd build && meson .. && ninja
    - cd $CI_PROJECT_DIR && PKG_CONFIG_PATH=./pacman/build/meson-uninstalled make build

include:
- template: Security/SAST.gitlab-ci.yml

sast:
  before_script:
    - ''
