# Install Python modules
python.install_sources(
        '__init__.py',
        'config.py',
        'pkginfo.py',
        'transaction.py',
        'action_database.py',
        'action_deptest.py',
        'action_query.py',
        'action_remove.py',
        'action_sync.py',
        'action_upgrade.py',
        'action_version.py',
        'action_optdepends.py',
        subdir: 'pycman',
)
